143 current  2024-05-25 22:07:21  24.05.20240419.5c24cf2       6.8.6-zen1                          *

diff --git a/build b/build
--- a/build
+++ b/build
@@ -3,10 +3,17 @@
 set -e
 
 #Change to change box setup
-BOX="default"
+BOX="desktop"
 
 pushd ~/nixos/
-
+notify(){
+    command -v notify-send > /dev/null
+    if [[ $? -ne 0 ]]; then 
+        return
+    else
+        notify-send "$@"
+    fi
+}
 # if git diff --quiet '*.nix' && [[ !( $1 =~ "*force*") ]] then
 #     echo "No changes. Exiting"
 #     # notify-send "No changes. Exiting"
@@ -22,11 +29,11 @@ git diff -U0 '*.nix'
 
 echo "Starting build"
 
-sudo nixos-rebuild switch --flake .#${BOX} &> build.log || (cat build.log | grep --color error && notify-send "ERROR BUILDING NIX" && exit 1)
+sudo nixos-rebuild switch --flake .#${BOX} &> build.log || (cat build.log | grep --color error && notify "ERROR BUILDING NIX" && exit 1)
 
 current=$(nixos-rebuild list-generations  | grep current)
 
 git commit -am "${current}"
 
 popd
-notify-send -e "good build" --icon=software-update-okay
+notify -e "good build" --icon=software-update-okay
